apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: wordpress
type: Opaque
data:
  # senha: wordpress123 (codificada em base64)
  mysql-root-password: d29yZHByZXNzMTIz
  mysql-password: d29yZHByZXNzMTIz
  mysql-database: d29yZHByZXNz 